spring:
  application:
    name: smart-doorbell-server
  datasource:
    url: jdbc:postgresql://localhost:5432/doorbell_db
    username: doorbell_user
    password: doorbell_pw
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
  jackson:
    time-zone: UTC
server:
  port: 8080


