openapi: 3.0.3
info:
  description: ""
  version: "1.0.0"
  title: "Smart Doorbell API"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
servers:
  - url: "{protocol}://{host}/api/v1"
    variables:
      protocol:
        enum: [ https, http ]
        default: http
      host:
        default: localhost:8080
paths:
  /users:
    get:
      operationId: getAllUsers
      tags:
        - user
      responses:
        "200":
          description: "Successful operation"
          content:
            application/json:
              schema:
                type: "array"
                items:
                  $ref: "#/components/schemas/UserResponse"
    post:
      operationId: createUser
      tags:
        - user
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UserRequest"
      responses:
        "200":
          description: "Successful creation"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UserResponse"
  /users/{userId}:
    parameters:
      - $ref: "#/components/parameters/UserId"
    get:
      operationId: getUserById
      tags:
        - user
      responses:
        "200":
          description: "Successful operation"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UserResponse"
        "404":
          $ref: "#/components/responses/NotFound"
    delete:
      operationId: deleteUser
      tags:
        - user
      responses:
        "204":
          description: "Successful deletion"
        "404":
          $ref: "#/components/responses/NotFound"
  /users/{userId}/doorbells:
    parameters:
      - $ref: "#/components/parameters/UserId"
    get:
      operationId: getAllDoorbells
      tags:
        - doorbell
      responses:
        "200":
          description: "Successful operation"
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/DoorbellResponse"
        "400":
          $ref: "#/components/responses/Invalid"
        "404":
          $ref: "#/components/responses/NotFound"
    post:
      operationId: createDoorbell
      tags:
        - doorbell
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/DoorbellRequest"
      responses:
        "200":
          description: "Successful creation"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/DoorbellResponse"
        "400":
          $ref: "#/components/responses/Invalid"
        "404":
          $ref: "#/components/responses/NotFound"
  /doorbells/{doorbellId}:
    parameters:
      - $ref: "#/components/parameters/DoorbellId"
    get:
      operationId: getDoorbell
      tags:
        - doorbell
      responses:
        "200":
          description: "Successful operation"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/DoorbellResponse"
        "404":
          $ref: "#/components/responses/NotFound"
    delete:
      operationId: deleteDoorbell
      tags:
        - doorbell
      responses:
        "204":
          description: "Successful deletion"
        "404":
          $ref: "#/components/responses/NotFound"
  /doorbells/{doorbellId}/open:
    post:
      operationId: openDoor
      tags:
        - doorbell_buzzer
      parameters:
        - $ref: "#/components/parameters/DoorbellId"
      responses:
        "204":
          description: "Successfully opened"
        "404":
          $ref: "#/components/responses/NotFound"
  /doorbells/{doorbellId}/close:
    post:
      operationId: closeDoor
      tags:
        - doorbell_buzzer
      parameters:
        - $ref: "#/components/parameters/DoorbellId"
      responses:
        "204":
          description: "Successfully closed"
        "404":
          $ref: "#/components/responses/NotFound"
  /doorbells/{doorbellId}/notify:
    parameters:
      - $ref: "#/components/parameters/DoorbellId"
    post:
      operationId: notify
      tags:
        - notification
      responses:
        "200":
          description: "Successful notification"
        "404":
          $ref: "#/components/responses/NotFound"
components:
  parameters:
    UserId:
      name: userId
      in: path
      description: "ID of user to which this doorbell belongs"
      required: true
      schema:
        type: integer
        format: int64
    DoorbellId:
      name: doorbellId
      in: path
      description: "ID of doorbell to retrieve"
      required: true
      schema:
        type: integer
        format: int64
  responses:
    NotFound:
      description: "Entity was not found"
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ErrorResponse"
  schemas:
    UserRequest:
      type: object
      properties:
        name:
          type: string
    UserResponse:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
    DoorbellRequest:
      type: object
      properties:
        name:
          type: string
    DoorbellResponse:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        is_opened:
          type: boolean
        is_connected:
          type: boolean
        last_notified:
          type: string
          format: date-time
    ErrorResponse:
      type: object
      properties:
        message:
          type: string